export default {
  af: [ 'af'],
  am: [ 'am'],
  ar: [ 'ar'],
  az: [ 'az'],
  be: [ 'be'],
  bg: [ 'bg'],
  bn: [ 'bn'],
  bs: [ 'bs'],
  ca: [ 'ca'],
  ceb: [ 'ph'],
  co: [ 'co'],
  cs: [ 'cz'],
  cy: [ 'cy'],
  da: [ 'dk'],
  de: [ 'de'],
  el: [ 'gr'],
  en: [ 'gb'],
  eo: [ 'us'],
  es: [ 'es'],
  et: [ 'et'],
  eu: [ 'eu'],
  fa: [ 'ir', 'iq'],
  fi: [ 'fi'],
  fr: [ 'de'],
  fy: [ 'fy'],
  ga: [ 'ga'],
  gd: [ 'gd'],
  gl: [ 'gl'],
  gu: [ 'gu'],
  ha: [ 'ne', 'ng'],
  haw: [ 'us'],
  hi: [ 'in'],
  hmn: [ 'cn', 'vn', 'la'],
  hr: [ 'hr'],
  ht: [ 'ht'],
  hu: [ 'hu'],
  hy: [ 'am'],
  id: [ 'id'],
  ig: [ 'ng'],
  is: [ 'is'],
  it: [ 'it'],
  iw: [ 'il'],
  ja: [ 'jp'],
  jw: [ 'id'],
  ka: [ 'ge'],
  kk: [ 'kz'],
  km: [ 'km'],
  kn: [ 'kn'],
  ko: [ 'kr', 'kp'],
  ku: [ 'ir', 'iq', 'tr', 'sy'],
  ky: [ 'ky'],
  la: [ 'la'],
  lb: [ 'lb'],
  lo: [ 'la'],
  lt: [ 'lt'],
  lv: [ 'lv'],
  mg: [ 'mg'],
  mi: [ 'nz', 'au'],
  mk: [ 'mk'],
  ml: [ 'ml'],
  mn: [ 'mn'],
  mr: [ 'mr'],
  ms: [ 'ms'],
  mt: [ 'mt'],
  my: [ 'my'],
  ne: [ 'ne'],
  nl: [ 'nl'],
  no: [ 'no'],
  ny: [ 'mw', 'zw'],
  pa: [ 'pa'],
  pl: [ 'pl'],
  ps: [ 'ps'],
  pt: [ 'pt'],
  ro: [ 'ro'],
  ru: [ 'ru'],
  sd: [ 'sd'],
  si: [ 'si'],
  sk: [ 'sk'],
  sl: [ 'sl'],
  sm: [ 'sm'],
  sn: [ 'sn'],
  so: [ 'so'],
  sq: [ 'al'],
  sr: [ 'sr'],
  st: [ 'st'],
  su: [ 'id'],
  sv: [ 'sv'],
  sw: [ 'tz', 'ke', 'ug', 'cg'],
  ta: [ 'in', 'lk'],
  te: [ 'in'],
  tg: [ 'tg'],
  th: [ 'th'],
  tl: [ 'tl'],
  tr: [ 'tr'],
  uk: [ 'ua'],
  ur: [ 'in', 'pk'],
  uz: [ 'uz'],
  vi: [ 'vi'],
  xh: [ 'za', 'zw'],
  yi: [ 'il'],
  yo: [ 'ng', 'bj', 'tg'],
  zh: [ 'cn'],
  'zh-TW': [ 'cn'],
  zu: [ 'za']
}
